cask_args appdir: '/Applications'

# Driver casks needed for e.g. Sonos
tap 'homebrew/cask-drivers'

# Utils
brew 'coreutils'
brew 'curl'
brew 'ffmpeg'
brew 'grc'
brew 'hey'
brew 'nvm'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'youtube-dlc'

# Apps
cask '1password'
cask 'airflow'
cask 'brave-browser'
cask 'calibre'
cask 'capture-one'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'ngrok'
cask 'notion'
cask 'signal'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'toggl-track'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'zoom'

# Drivers
cask 'sonos'
