cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'heroku-toolbelt'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'unrar'
brew 'wget'

cask 'appcleaner'
cask 'arduino'
cask 'atom'
cask 'charles'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'little-snitch'
cask 'sketch'
cask 'slack'
cask 'sonos'
cask 'spectacle'
cask 'transmit'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
