#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Install Atom packages through the Atomfile
echo "› apm install --packages-file Atomfile"
apm install --packages-file Atomfile

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
